language: ruby
rvm:
- 2.1
- 2.2
- ruby-head
cache: bundler
before_script:
- export COVERAGE=true
script:
- bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
matrix:
  allow_failures:
  - rvm: ruby-head
